spring:
  application:
    name: eureka-server #应用名称
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/ #Eureka Server地址
    register-with-eureka:
      false #因为自己是注册中心，所以不注册自己
    fetch-registry:
      false